{% set version = "1.0.0" %}

package:
  name: symucore
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - {{ compiler('cxx') }}  #[linux]
    - make
    - cmake
  host:
    - boost
    - boost-cpp
  run:
    - boost
    - boost-cpp


about:
  home: https://github.com/licit-lab/symucore
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Core objects and algorithms for the SymuVia ecosystem.
  dev_url: https://github.com/licit-lab/symucore
